tools:
    external_code_coverage: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        avoid_closing_tag: true
        avoid_duplicate_types: true
        avoid_perl_style_comments: true
        avoid_tab_indentation: true
        blank_line_after_namespace_declaration: true
        classes_in_camel_caps: true
        ensure_lower_case_builtin_functions: true
        function_in_camel_caps: true
        lowercase_basic_constants: true
        lowercase_php_keywords: true
        missing_arguments: true
        newline_at_end_of_file: true
        no_short_open_tag: true
        no_space_inside_cast_operator: true
        no_trailing_whitespace: true
        parameter_doc_comments: true
        prefer_unix_line_ending: true
        require_scope_for_methods: true
        require_scope_for_properties: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        single_namespace_per_use: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        prefer_while_loop_over_for_loop: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_space_after_cast: true
        no_global_keyword: true
        no_exit: true
        function_body_start_on_new_line: true
        avoid_multiple_statements_on_same_line: true
        too_many_arguments: true
        require_php_tag_first: true
        argument_type_checks: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true
