tools:
    external_code_coverage: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            before_parentheses:
                closure_definition: true